[491768] Change classpathScope to 'runtime' because of NoClassDefFoundError for JETException
Change-Id: I5381cd4d27db4b9943f12b1395e4db94f7fe18a0
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>