maven tycho (#1459)
* use upstream

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

* <skipPomGeneration>true</skipPomGeneration>

* adjusted POM with configurations and latest by default

* currently latest TP from milestores

* xtend.core compiles

* added missing maven properties

* xtend-maven-plugin configured in pluginManagement

* added xtext-dev-bom to parent

* root project as Maven project (tycho-pom -> pom)

* xtend.core as Maven/Tycho project

* GitHub Actions workflow

* build with Java 17

Error:  org.eclipse.m2e.core 2.0.5.20221128-1757 requires Execution Environment that matches (&(osgi.ee=JavaSE)(version=17)) but the current resolution context uses [a.jre.javase 11.0.0]
Error:  Cannot resolve target definition:
Error:    Software being installed: org.eclipse.m2e.feature.feature.group 2.1.2.20221130-2239
Error:    Missing requirement: org.eclipse.m2e.core 2.0.5.20221128-1757 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=17))' but it could not be found
Error:    Cannot satisfy dependency: org.eclipse.m2e.feature.feature.group 2.1.2.20221130-2239 depends on: org.eclipse.equinox.p2.iu; org.eclipse.m2e.core [2.0.5.20221128-1757,2.0.5.20221128-1757]

* POM only builds xtend.core

* xtend.core.tests compiles

* renamed test classes to follow surefire convention

* xtend.core.tests executed with tycho-surefire

* skip testCompileSymlinkedResource on Windows

because of symlinks

* ide.common compiles

* xtend.ide.common as Maven/Tycho project

* xtend.ide as Maven/Tycho project

* xtend.ide.tests output to target/classes

* converted to Maven project

* refer to .target with a file path

* ide.tests.data as Maven/Tycho project

* ide.tests run in the build

* xvfb in Linux GitHub Actions

* Revert "skip testCompileSymlinkedResource on Windows"

This reverts commit 7176e61fbefe923ccb6515f22505f0c651c65796.

* disabled Windows on GitHub Actions

it's too flaky for UI tests

* xtend.m2e Maven nature

* xtend.standalone as Maven project

* .ide.tests no test source folders: needed by .performance.tests

* performance.tests in the build

* xtend.doc in the build

* xtend.examples built

* fixed openPreferences in SWTBot tests for macOS

* swtbot.tests as Maven project

* xtend-maven-plugin in performance.tests

* additional TP environment aarch64 for macOS

* SWTBot tests in the build

* moved swtbot tests as last

* correctly ignore .DS_Store

* new p2 repository project

* updated classpath of maven archetype and plugin

* added new maven.releng project

* GitHub Actions job for Maven artifacts

* removed the old maven-pom.xml

* removed reference to gradle local-repo

* -PuseJenkinsSnapshots in GitHub Actions as well

* updated Jenkins build files

* archive build directory in Jenkins

* some "x-friend" for core.tests

* removed gradle buildcommand from root project

* temurin-jdk17-latest first in Jenkinsfile

* [#1212] add workaround for RebuildAffectedResourcesTest flakyness
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

* extracted tests from suite

* move TP latest first in Jenkinsfile

* run tycho build first in Jenkins

* GitHub Actions: if condition for xvfb-run on Linux

* updated build for signing/deploy

* jenkinsfile for deploying Maven artifacts

* -PuseJenkinsSnapshots when maven deploy

* also deploy xtend.ide.common

* always use project.version for xtext deps

* -P useJenkinsSnapshots in Jenkins

* removed old xtend.maven.releng project

* xtend.maven.parent inherits from the main parent

* harmonized parent POM with xtext-lib

* exec-maven-plugin

* disabled signing and javadoc profile

* tycho.tests.parent to aggregator

* bumped version 2.31.0 in POMs

* removed gradle files

* don't sign maven artifacts

---------

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>
Co-authored-by: Christian Dietrich <christian.dietrich@itemis.de>